TEAM_CITY_MAP = {
    "1. FC Heidenheim 1846": "Heidenheim",
    "1. FC Köln": "Cologne",
    "1. FC Union Berlin": "Berlin",
    "1. FSV Mainz 05": "Mainz",
    "AC Milan": "Milan",
    "AC Monza": "Monza",
    "ACF Fiorentina": "Florence",
    "AFC Bournemouth": "Bournemouth",
    "AS Roma": "Rome",
    "Arminia Bielefeld": "Bielefeld",
    "Arsenal FC": "London",
    "Aston Villa FC": "Birmingham",
    "Atalanta BC": "Bergamo",
    "Athletic Club": "Bilbao",
    "Bayer 04 Leverkusen": "Leverkusen",
    "Benevento Calcio": "Benevento",
    "Bologna FC 1909": "Bologna",
    "Borussia Dortmund": "Dortmund",
    "Borussia Mönchengladbach": "Mönchengladbach",
    "Brentford FC": "London",
    "Brighton & Hove Albion FC": "Brighton",
    "Burnley FC": "Burnley",
    "CA Osasuna": "Pamplona",
    "CD Leganés": "Leganés",
    "Cagliari Calcio": "Cagliari",
    "Chelsea FC": "London",
    "Club Atlético de Madrid": "Madrid",
    "Como 1907": "Como",
    "Crystal Palace FC": "London",
    "Cádiz CF": "Cádiz",
    "Deportivo Alavés": "Vitoria-Gasteiz",
    "Eintracht Frankfurt": "Frankfurt",
    "Elche CF": "Elche",
    "Empoli FC": "Empoli",
    "Everton FC": "Liverpool",
    "FC Augsburg": "Augsburg",
    "FC Barcelona": "Barcelona",
    "FC Bayern München": "Munich",
    "FC Crotone": "Crotone",
    "FC Internazionale Milano": "Milan",
    "FC Schalke 04": "Gelsenkirchen",
    "FC St. Pauli 1910": "Hamburg",
    "Frosinone Calcio": "Frosinone",
    "Fulham FC": "London",
    "Genoa CFC": "Genoa",
    "Getafe CF": "Getafe",
    "Girona FC": "Girona",
    "Granada CF": "Granada",
    "Hellas Verona FC": "Verona",
    "Hertha BSC": "Berlin",
    "Holstein Kiel": "Kiel",
    "Ipswich Town FC": "Ipswich",
    "Juventus FC": "Turin",
    "Leeds United FC": "Leeds",
    "Leicester City FC": "Leicester",
    "Levante UD": "Valencia",
    "Liverpool FC": "Liverpool",
    "Luton Town FC": "Luton",
    "Manchester City FC": "Manchester",
    "Manchester United FC": "Manchester",
    "Newcastle United FC": "Newcastle upon Tyne",
    "Norwich City FC": "Norwich",
    "Nottingham Forest FC": "Nottingham",
    "Parma Calcio 1913": "Parma",
    "RB Leipzig": "Leipzig",
    "RC Celta de Vigo": "Vigo",
    "RCD Espanyol de Barcelona": "Barcelona",
    "RCD Mallorca": "Palma de Mallorca",
    "Rayo Vallecano de Madrid": "Madrid",
    "Real Betis Balompié": "Seville",
    "Real Madrid CF": "Madrid",
    "Real Sociedad de Fútbol": "San Sebastián",
    "Real Valladolid CF": "Valladolid",
    "SC Freiburg": "Freiburg",
    "SD Eibar": "Eibar",
    "SD Huesca": "Huesca",
    "SS Lazio": "Rome",
    "SSC Napoli": "Naples",
    "SV Darmstadt 98": "Darmstadt",
    "SV Werder Bremen": "Bremen",
    "Sevilla FC": "Seville",
    "Sheffield United FC": "Sheffield",
    "Southampton FC": "Southampton",
    "SpVgg Greuther Fürth 1903": "Fürth",
    "Spezia Calcio": "La Spezia",
    "TSG 1899 Hoffenheim": "Sinsheim",
    "Torino FC": "Turin",
    "Tottenham Hotspur FC": "London",
    "UC Sampdoria": "Genoa",
    "UD Almería": "Almería",
    "UD Las Palmas": "Las Palmas",
    "US Cremonese": "Cremona",
    "US Lecce": "Lecce",
    "US Salernitana 1919": "Salerno",
    "US Sassuolo Calcio": "Sassuolo",
    "Udinese Calcio": "Udine",
    "Valencia CF": "Valencia",
    "Venezia FC": "Venice",
    "VfB Stuttgart": "Stuttgart",
    "VfL Bochum 1848": "Bochum",
    "VfL Wolfsburg": "Wolfsburg",
    "Villarreal CF": "Villarreal",
    "Watford FC": "Watford",
    "West Bromwich Albion FC": "West Bromwich",
    "West Ham United FC": "London",
    "Wolverhampton Wanderers FC": "Wolverhampton",
}
